Repository Sylius/SyliusAdminApiBundle, pull requests merged in 2022-06, with the labels that each got.

#16 Drop support for Sylius 1.9
  .github/workflows/build.yml
  composer.json
Labels: Maintenance

#17 Change branch alias to 1.11-dev
  composer.json
Labels: Bug, Maintenance

#18 Change branch alias to 1.12-dev
  composer.json
Labels: Maintenance

#12 Add full CRUD for payment methods
  Form/Type/OrderType.php
  Resources/config/app/config.yml
  Resources/config/grids/payment_method.yml
  Resources/config/routing/payment_method.yml
  Resources/config/services/form.xml
  composer.json
  tests/Controller/PaymentMethodApiTest.php
  tests/DataFixtures/ORM/resources/gateway_config.yml
  tests/DataFixtures/ORM/resources/payment_methods.yml
  tests/Responses/payment_method/create_response.json
  tests/Responses/payment_method/index_response.json
Labels: Feature
